### ISSUE TITLE
Drasi API not available

### ISSUE THREAD

**Issue by aravind-venkedeshwaran** [drasi-project/drasi-platform#101]
### Steps to reproduce

I encountered timeout issues during installation while following the Drasi [getting-started ](https://drasi.io/getting-started/)guide. When attempting to create a source using `drasi apply -f ./resources/hello-world-source.yaml`, I received the error: `Error: drasi API not available`. The timeouts occur during the Drasi installation process. But drasi seems to works but Drasi-API is the issue. 

### Observed behavior

<img width="826" alt="Screenshot 2024-10-28 at 1 05 40 PM" src="https://github.com/user-attachments/assets/c60e348a-f229-4a09-99bd-3fae78a2edb5">
<img width="842" alt="Screenshot 2024-10-28 at 2 21 34 PM" src="https://github.com/user-attachments/assets/540462a6-82e2-4f96-a89a-10ac82511c5b">

### Desired behavior

Expected: Create all the deployments mentioned in the guide and explore drasi

### Drasi Version

Drasi CLI version: 0.1.4

### Operating system

Linux d78b2c86c314 6.1.61-85.141.amzn2023.aarch64 #1 SMP Wed Nov  8 00:38:50 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by NValsan** [comment]
Thank you for filing this issue. We will look into this and share our findings. If there is any additional info you'd like to share about the issue, please do let us know.

**Comment by ruokun-niu** [comment]
Hi @aravind-venkedeshwaran, thank you for filing the issue.
 I suspect that something went wrong during the install. Can you try running `kubectl get pods -n drasi-system` to check the status of the pods?

**Comment by aravind-venkedeshwaran** [comment]
`kubectl get pods -n drasi-system`
<img width="873" alt="Screenshot 2024-11-04 at 11 35 52 AM" src="https://github.com/user-attachments/assets/1c41a1ac-6192-4852-a083-58d34f0063fb">

Event of `drasi-resource-provider-7dcd95db5c-tv99f` pod
<img width="1685" alt="Screenshot 2024-11-04 at 11 41 28 AM" src="https://github.com/user-attachments/assets/5f3c6842-6916-4634-9494-6774bf527374">


Event of `otel-collector-8c7496f88-hrd2g ` pod

<img width="1664" alt="Screenshot 2024-11-04 at 11 45 59 AM" src="https://github.com/user-attachments/assets/fc9aaffe-db16-4ecf-8bb7-7aa47f901252">

**Comment by aravind-venkedeshwaran** [comment]
Seems like `kubernetes-provider:0.1.3` Doesn't fit for my machine
<img width="1325" alt="Screenshot 2024-11-04 at 12 09 36 PM" src="https://github.com/user-attachments/assets/b741b91a-4ccd-44e0-9568-0f3f5964f826">

**Comment by ruokun-niu** [comment]
Hi @aravind-venkedeshwaran, thanks for providing the screenshots. Seems like this is due to an image architecture issue. 

Our `0.1.3` images were actually not multi-arch images. However, we recently did a new release [(0.1.5)](https://github.com/drasi-project/drasi-platform/releases/tag/0.1.5) where all of the images are built as multi-arch images. This should solve the issue. 

I'd recommend re-installing the Drasi CLI using the installation script and re-deploying the newest version of Drasi in a new Kubernetes cluster.

**Comment by aravind-venkedeshwaran** [comment]
Thanks @ruokun-niu 👍

**Comment by ruokun-niu** [comment]
Hi @aravind-venkedeshwaran, just a heads up that I am closing this issue. Feel free to open it again if there are any new issues :)
