### ISSUE TITLE
Hostname in 'drasi list query' seems to be not on the same line as others

### ISSUE THREAD

**Issue by ytimocin** [drasi-project/drasi-platform#76]
### Steps to reproduce

1. Apply a query configuration
2. Run `drasi list query`
3. See the following result in the next section

### Observed behavior

![image](https://github.com/user-attachments/assets/30b82350-06b3-4f16-a2aa-2426da676924)

### Desired behavior

They all need to be on the same line.

### Drasi Version

edge

### Operating system

macOS, Apple M1 Pro, Sequoia 15

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by ruokun-niu** [comment]
Thanks @ytimocin !

**Comment by ruokun-niu** [comment]
Hi @ytimocin, the fix for this has just been merged into main. Thanks!
