### ISSUE TITLE
Kafka reaction

### ISSUE THREAD

**Issue by tiagomelo** [drasi-project/drasi-platform#98]
### Overview of feature request

According with the currently available reactions, we have
- Azure Event Grid
- Debug
- SignalR
- Gremlin
- Dataverse

Do you have any plans for adding new reactions, like Kafka, for example? It would be useful to stream continuous queries results to it.

Another question: do you have a guide for writing custom reactions, so I can decide what to do with continuous queries results?

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by tiagomelo** [comment]
Actually I just cloned the project and saw [debezium](https://github.com/drasi-project/drasi-platform/tree/main/reactions/debezium/debezium-reaction), which seems to enable streaming to a Kafka topic. I'll take a look at it.

**Comment by agentofreality** [comment]
hi @tiagomelo,

I responded to your other issue (https://github.com/drasi-project/drasi-platform/issues/99) with detail that is also relevant here. As you have already discovered, we would suggest you try the Debezium Reaction for downstream Kafka integration. 

We would love to hear how your experimentation with Drasi goes and whether the Debezium Reaction is sufficient, or whether there are Kafka requirements that might require a specific Kafka Reaction.

**Comment by tiagomelo** [comment]
Thanks.
