### ISSUE TITLE
Guide on writing custom Reactions

### ISSUE THREAD

**Issue by tiagomelo** [drasi-project/drasi-platform#99]
### Overview of feature request

It would be wonderful if we could write custom Reactions. To accomplish that, it would be nice to have a guide on creating them; if you could point me a general guide on how can I write a custom Reaction, I'd be more than happy on writing that guide.

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by agentofreality** [comment]
Hello @tiagomelo,

Sources and Reactions are the first points of extensibility we expose in Drasi, so yes, it is possible to write a custom Reaction.

We have some documentation that we are in the process of updating and will publish shortly that describes this process Also, one of the team's main areas of focus at the moment is improving the developer experience with better docs, examples, and tools.

You can actually see the unpublished document for writing custom sources in the docs repo here: https://github.com/drasi-project/docs/blob/preview/docs/content/how-to-guides/extend-drasi/implement-a-reaction.md

The existing Reactions (https://github.com/drasi-project/drasi-platform/tree/main/reactions) are all written using this extensibility model, so can provide a guide for you. One key element you need to define is a ReactionProvider definition and register that with a Drasi environment, so Drasi knows how to instantiate your Reaction when it is used.

The ReactionProvider definitions for the default set of Reactions are all contained in this file: https://github.com/drasi-project/drasi-platform/blob/main/cli/service/resources/default-reaction-providers.yaml, that gets applied as part of the Drasi install process.

Registering a new ReactionProvider is done using the drasi cli command 'drasi apply' as described here: https://drasi.io/reference/command-line-interface/#drasi-apply

If you want to use this info to try to write a custom Reaction, we would be happy to assist you by answering any questions and helping with issues that may arise. And if that results in you being able to contribute some docs back to the community on how you developed your Reaction, or feedback for us on how we could improve the Reaction development model/process that would be greatly appreciated.

Let us know if you need anything, and consider coming and joining our discord channel where the team are most active and able to jump in and answer questions (https://aka.ms/drasidiscord)

**Comment by tiagomelo** [comment]
Thanks!
